name: Maven Release
on:
  release:
    types: [ published ]
jobs:
  publish:
    name: Maven Artifact Publisher (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - name: Check out source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142 # v3.3.0
        with:
          cache: maven
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Login to Docker repository
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Release with Maven
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_profiles: release
          maven_args: >
            -Drevision=${{ github.event.release.tag_name }}
            -ntp -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error -Ddocker.showLogs=true
            -DskipNexusStagingDeployMojo=true -Dgpg.skip=true
            -Ddocker.registry.username=${{ secrets.DOCKER_USERNAME }}
            -Ddocker.registry.account=${{ secrets.DOCKER_REGISTRY_ACCOUNT }}
            -Ddocker.registry.password=${{ secrets.DOCKER_PASSWORD }}
